---
- name: create folder
  file:
    path: "{{ node_exporter_path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0750

- name: download release
  get_url:
    url: "{{ node_exporter_release }}"
    dest: "{{ node_exporter_path }}/.node_exporter.tgz"
    checksum: "sha256:{{ node_exporter_sha256 }}"
  register: release

- name: extract release
  unarchive:
    src: "{{ node_exporter_path }}/.node_exporter.tgz"
    dest: "{{ node_exporter_path }}"
    extra_opts: "--strip-components=1"
    owner: nobody
    group: nogroup
    remote_src: yes
  when: release.changed
  notify: restart node_exporter

- name: template service
  template:
    src: node_exporter.service
    dest: /etc/systemd/system/
  notify: restart node_exporter

- name: enable service
  systemd:
    name: node_exporter
    enabled: yes
    daemon_reload: yes
