---
- name: add signing key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6

- name: add repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: install packages
  apt:
    name:
      - grafana
