---
- hosts: all
  roles:
    - role: alxndr42.commons.nginx
      tags: nginx
      when: nginx
    - role: alxndr42.commons.certbot
      tags: certbot
      when: certbot

- hosts: monitoring
  roles:
    - role: pushgateway
      tags: pushgateway
      when: pushgateway
    - role: prometheus
      tags: prometheus
      when: prometheus
    - role: grafana
      tags: grafana
      when: grafana

- hosts: monitoring_targets
  roles:
    - role: node-exporter
      tags: node-exporter
      when: node_exporter
    - role: nginx-prometheus
      tags: nginx-prometheus
      when: nginx_prometheus
