---
- hosts: monitoring
  roles:
    - role: alertmanager
      tags: alertmanager
      when: alertmanager
    - role: prometheus
      tags: prometheus
    - role: grafana
      tags: grafana

- hosts: monitoring_targets
  roles:
    - role: node-exporter
      tags: node-exporter
