---
- hosts: all
  roles:
    - role: nginx
      tags: nginx
      when: nginx
    - role: certbot
      tags: certbot
      when: certbot

- hosts: monitoring
  roles:
    - role: alertmanager
      tags: alertmanager
      when: alertmanager
    - role: prometheus
      tags: prometheus
    - role: grafana
      tags: grafana

- hosts: monitoring_targets
  roles:
    - role: node-exporter
      tags: node-exporter
