---
alertmanager: true
alertmanager_release: https://github.com/prometheus/alertmanager/releases/download/v0.25.0/alertmanager-0.25.0.linux-amd64.tar.gz
alertmanager_sha256: "206cf787c01921574ca171220bb9b48b043c3ad6e744017030fed586eb48e04b"
alertmanager_etc: /etc/alertmanager
alertmanager_data: /var/lib/alertmanager
alertmanager_path: /opt/alertmanager
alertmanager_listen: 127.0.0.1:9093
alertmanager_url: http://127.0.0.1:9093
