---
alertmanager: true
alertmanager_release: https://github.com/prometheus/alertmanager/releases/download/v0.24.0/alertmanager-0.24.0.linux-amd64.tar.gz
alertmanager_sha256: "6fa982232ae7be5524f5b3cd4e90b7c6a75086368200c917644eaa3e806555dc"
alertmanager_etc: /etc/alertmanager
alertmanager_data: /var/lib/alertmanager
alertmanager_path: /opt/alertmanager
alertmanager_listen: 127.0.0.1:9093
alertmanager_url: http://127.0.0.1:9093
