---
- name: create password file
  shell: dd if=/dev/random bs=1M count=1 status=none | sha256sum | awk '{print $1}' > {{ password_file }}
  args:
    creates: "{{ password_file }}"
  register: password

- name: set password file ownership/mode
  file:
    path: "{{ password_file }}"
    owner: prometheus
    group: prometheus
    mode: 0640
  when: password.changed

- name: get password
  command: cat {{ password_file }}
  check_mode: no
  changed_when: false
  register: password

- set_fact:
    prometheus_username: "{{ username }}"
    prometheus_password: "{{ password.stdout }}"
