---
- name: generate password
  shell: echo -n "{{ password }}" | openssl passwd -stdin -apr1 -salt "{{ username }}"
  check_mode: no
  changed_when: false
  register: openssl

- name: update htpasswd file
  lineinfile:
    path: /etc/nginx/htpasswd.prometheus
    regexp: "^{{ username }}:"
    line: "{{ username }}:{{ openssl.stdout }}"
    create: yes
    owner: root
    group: www-data
    mode: 0640
  notify: reload nginx
