---
prometheus: true
prometheus_release: https://github.com/prometheus/prometheus/releases/download/v2.35.0/prometheus-2.35.0.linux-amd64.tar.gz
prometheus_sha256: "e4546960688d1c85530ec3a93e109d15b540f3251e1f4736d0d9735e1e857faf"
prometheus_etc: /etc/prometheus
prometheus_data: /var/lib/prometheus
prometheus_path: /opt/prometheus
prometheus_retention_time: "15d"
prometheus_listen: 127.0.0.1:9090
prometheus_url: http://127.0.0.1:9090
