---
prometheus_release: https://github.com/prometheus/prometheus/releases/download/v2.32.1/prometheus-2.32.1.linux-amd64.tar.gz
prometheus_sha256: "f08e96d73330a9ee7e6922a9f5b72ea188988a083bbfa9932359339fcf504a74"
prometheus_etc: /etc/prometheus
prometheus_data: /var/lib/prometheus
prometheus_path: /opt/prometheus
prometheus_retention_time: "15d"
prometheus_listen: 127.0.0.1:9090
prometheus_url: http://127.0.0.1:9090
